// Code generated by aliensbot. DO NOT EDIT.
// source: room_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-server/module/room/core"
	"github.com/KylinHe/aliensboot-server/protocol"
)


//
func handleRespondJoinGame(authID int64, gateID string, request *protocol.RespondJoinGame) {
	room := core.RoomManager.GetRoomByPlayerID(authID)
	room.JoinGame(authID)
}
