// Code generated by aliensbot. DO NOT EDIT.
// source: room_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-server/module/room/core"
	"github.com/KylinHe/aliensboot-server/protocol"
)

//
func handleBroadcastViewer(authID int64, gateID string, request *protocol.BroadcastViewer) {
	room := core.RoomManager.GetRoomByPlayerID(authID)
	push := &protocol.Response{Room: &protocol.Response_BroadcastViewerRet{BroadcastViewerRet: &protocol.BroadcastViewerRet{
		Data: request.GetData(),
	}}}
	room.BroadcastViewer(push)
}
