// Code generated by aliensboot. DO NOT EDIT.
// source: module defaultmodule
package rpc

import (
	"github.com/KylinHe/aliensboot-server/protocol"
)

var Defaultmodule = &defaultmoduleRPCHandler{&rpcHandler{name:"defaultmodule"}}


type defaultmoduleRPCHandler struct {
	*rpcHandler
}


func (this *defaultmoduleRPCHandler) Benchmark(node string, request *protocol.Benchmark) *protocol.BenchmarkRet {
	message := &protocol.Request{
		Defaultmodule:&protocol.Request_Benchmark{
			Benchmark:request,
		},
	}
	messageRet := this.Request(node, message)
	return messageRet.GetBenchmarkRet()
}


func (this *defaultmoduleRPCHandler) TestBenchmark(authId int64, node string, request *protocol.Benchmark) (*protocol.BenchmarkRet, error) {
	message := &protocol.Request{
		Defaultmodule:&protocol.Request_Benchmark{
			Benchmark:request,
		},
	}
	messageRet, err := this.TestRequest(authId, node, message)
	return messageRet.GetBenchmarkRet(), err
}



