// Code generated by aliensboot. DO NOT EDIT.
// source: gate_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-server/module/gate/network"
	"github.com/KylinHe/aliensboot-server/protocol"
)

//
func handleBindService(authID int64, gateID string, request *protocol.BindService, response *protocol.BindServiceRet) {
	response.Result = network.Manager.BindService(request.GetAuthId(), request.GetBinds())
}
