// Code generated by aliensboot. DO NOT EDIT.
// source: gate_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-server/module/gate/network"
	"github.com/KylinHe/aliensboot-server/protocol"
)

//
func handleBindServiceMultiAuth(authID int64, gateID string, request *protocol.BindServiceMultiAuth) {
	network.Manager.BindServiceMultiAuth(request.GetAuthIds(), request.GetBinds())
}
