// Code generated by aliensbot. DO NOT EDIT.
// source: game_interface.proto
package service

import "github.com/KylinHe/aliensboot-server/protocol"


//
func handleGetRoleInfo(authID int64, gateID string, request *protocol.GetRoleInfo, response *protocol.GetRoleInfoRet) {

}


