// Code generated by aliensbot. DO NOT EDIT.
// source: module scene
package rpc

import (
	"github.com/KylinHe/aliensboot-server/protocol"
)

var Scene = &sceneRPCHandler{&rpcHandler{name: "scene"}}

type sceneRPCHandler struct {
	*rpcHandler
}

func (this *sceneRPCHandler) EntityCall(node string, request *protocol.EntityCall) error {
	message := &protocol.Request{
		Scene: &protocol.Request_EntityCall{
			EntityCall: request,
		},
	}
	return this.Send(node, message)
}

func (this *sceneRPCHandler) LoginScene(node string, request *protocol.LoginScene) error {
	message := &protocol.Request{
		Scene: &protocol.Request_LoginScene{
			LoginScene: request,
		},
	}
	return this.Send(node, message)
}

func (this *sceneRPCHandler) MoveScene(node string, request *protocol.MoveScene) error {
	message := &protocol.Request{
		Scene: &protocol.Request_MoveScene{
			MoveScene: request,
		},
	}
	return this.Send(node, message)
}

func (this *sceneRPCHandler) MigrateIn(node string, request *protocol.MigrateIn) error {
	message := &protocol.Request{
		Scene: &protocol.Request_MigrateIn{
			MigrateIn: request,
		},
	}
	return this.Send(node, message)
}

func (this *sceneRPCHandler) MigrateOut(node string, request *protocol.MigrateOut) error {
	message := &protocol.Request{
		Scene: &protocol.Request_MigrateOut{
			MigrateOut: request,
		},
	}
	return this.Send(node, message)
}
