// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: game_model.proto

package protocol

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Role struct {
	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id" gorm:"AUTO_INCREMENT"`
	Uid      int64  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty" bson:"uid" unique:"true"`
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty" bson:"nickname"`
	SpaceID  string `protobuf:"bytes,4,opt,name=spaceID,proto3" json:"spaceID,omitempty" bson:"spaceID"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptorGameModel, []int{0} }

func (m *Role) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Role) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Role) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Role) GetSpaceID() string {
	if m != nil {
		return m.SpaceID
	}
	return ""
}

func init() {
	proto.RegisterType((*Role)(nil), "protocol.Role")
}
func (m *Role) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Role) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintGameModel(dAtA, i, uint64(m.Id))
	}
	if m.Uid != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintGameModel(dAtA, i, uint64(m.Uid))
	}
	if len(m.Nickname) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintGameModel(dAtA, i, uint64(len(m.Nickname)))
		i += copy(dAtA[i:], m.Nickname)
	}
	if len(m.SpaceID) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintGameModel(dAtA, i, uint64(len(m.SpaceID)))
		i += copy(dAtA[i:], m.SpaceID)
	}
	return i, nil
}

func encodeVarintGameModel(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Role) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovGameModel(uint64(m.Id))
	}
	if m.Uid != 0 {
		n += 1 + sovGameModel(uint64(m.Uid))
	}
	l = len(m.Nickname)
	if l > 0 {
		n += 1 + l + sovGameModel(uint64(l))
	}
	l = len(m.SpaceID)
	if l > 0 {
		n += 1 + l + sovGameModel(uint64(l))
	}
	return n
}

func sovGameModel(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGameModel(x uint64) (n int) {
	return sovGameModel(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Role) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGameModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Role: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Role: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGameModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			m.Uid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGameModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Uid |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nickname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGameModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGameModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nickname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpaceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGameModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGameModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpaceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGameModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGameModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGameModel(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGameModel
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGameModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGameModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthGameModel
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGameModel
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGameModel(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGameModel = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGameModel   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("game_model.proto", fileDescriptorGameModel) }

var fileDescriptorGameModel = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x31, 0x4e, 0xc3, 0x30,
	0x18, 0x46, 0xe5, 0xa6, 0x82, 0x62, 0x21, 0x40, 0x66, 0xb1, 0x10, 0x4a, 0x22, 0x8b, 0xa1, 0x03,
	0x24, 0x03, 0x4c, 0xd9, 0x08, 0x74, 0xe8, 0x40, 0x91, 0xac, 0x32, 0x47, 0x49, 0x6c, 0x8c, 0x45,
	0x9c, 0xbf, 0xa4, 0xf1, 0x1d, 0x91, 0x58, 0x38, 0x41, 0x84, 0x72, 0x84, 0x9c, 0x00, 0xd5, 0xa1,
	0x4c, 0xf6, 0xa7, 0xf7, 0xde, 0xf0, 0xe3, 0x33, 0x95, 0x1b, 0x99, 0x19, 0x10, 0xb2, 0x8a, 0x36,
	0x0d, 0xb4, 0x40, 0x66, 0xee, 0x29, 0xa1, 0xba, 0xb8, 0x51, 0xba, 0x7d, 0xb3, 0x45, 0x54, 0x82,
	0x89, 0x15, 0x28, 0x88, 0x1d, 0x29, 0xec, 0xab, 0x5b, 0x6e, 0xb8, 0xdf, 0x18, 0xb2, 0x2f, 0x84,
	0xa7, 0x1c, 0x2a, 0x49, 0xee, 0xf0, 0x44, 0x0b, 0x8a, 0x42, 0x34, 0xf7, 0xd2, 0xab, 0xa1, 0x0b,
	0xc2, 0x62, 0x0b, 0x75, 0xc2, 0x32, 0x2d, 0x58, 0xa8, 0xa0, 0x31, 0x09, 0xbb, 0x7f, 0x59, 0x3f,
	0x67, 0xcb, 0xd5, 0x03, 0x5f, 0x3c, 0x2d, 0x56, 0x6b, 0xc6, 0x27, 0x5a, 0x90, 0x08, 0x7b, 0x56,
	0x0b, 0x3a, 0x71, 0xd9, 0xe5, 0xd0, 0x05, 0x74, 0xcc, 0xec, 0x2e, 0xb3, 0xb5, 0xfe, 0xb0, 0x32,
	0x61, 0x6d, 0x63, 0x25, 0xe3, 0x3b, 0x91, 0xc4, 0x78, 0x56, 0xeb, 0xf2, 0xbd, 0xce, 0x8d, 0xa4,
	0x5e, 0x88, 0xe6, 0x47, 0xe9, 0xf9, 0xd0, 0x05, 0xa7, 0x63, 0xb4, 0x27, 0x8c, 0xff, 0x4b, 0xe4,
	0x1a, 0x1f, 0x6e, 0x37, 0x79, 0x29, 0x97, 0x8f, 0x74, 0xea, 0x7c, 0x32, 0x74, 0xc1, 0xc9, 0xe8,
	0xff, 0x01, 0xc6, 0xf7, 0x4a, 0x7a, 0xfc, 0xd9, 0xfb, 0xe8, 0xbb, 0xf7, 0xd1, 0x4f, 0xef, 0xa3,
	0xe2, 0xc0, 0x9d, 0x78, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x08, 0xe5, 0xf9, 0xeb, 0x2f, 0x01,
	0x00, 0x00,
}
