// Code generated by aliensbot. DO NOT EDIT.
// source: gate_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-core/protocol/base"
	"github.com/KylinHe/aliensboot-server/module/gate/network"
	"github.com/KylinHe/aliensboot-server/module/gate/route"
	"github.com/KylinHe/aliensboot-server/protocol"
)




//
func handlePushMessage(authID int64, gateID string, request *protocol.PushMessage) {
	msgID := route.GetServiceSeq(request.GetService())
	msg := &base.Any{Id: msgID, Value: request.GetData()}
	authID = request.GetAuthID()
	if authID == -1 {
		network.Manager.Broadcast(msg)
	} else if authID > 0 {
		network.Manager.Push(authID, msg)
	}
}
