# -------------------------------- Service ---------------------------
#
service:
  name: room
  port: 19119
  #
  # registered in the service center [zookeepr or etcd], exposed to the
  # external address information
  #
  address:
  #
  # service lbs strategy options[polling,hashing]
  #
  lbs: Polling
# -------------------------------- Database ---------------------------
database:
  address: 127.0.0.1:27017
  name: db_room
# -------------------------------- Cache ---------------------------
cache:
  address: 127.0.0.1:6379
  password:
# -------------------------------- Custom ---------------------------
#param1: 11111111
#param2: e434e639