// Code generated by aliensboot. DO NOT EDIT.
// source: scene_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-core/exception"
	"github.com/KylinHe/aliensboot-core/mmo"
	"github.com/KylinHe/aliensboot-server/module/scene/entity"
	"github.com/KylinHe/aliensboot-server/protocol"
)

//
func handleMoveScene(authID int64, gateID string, request *protocol.MoveScene) {
	//获取空间所在的服务器节点
	err := mmo.MigrateTo(mmo.EntityID(request.GetSpaceID()), entity.GetPlayerID(authID))
	if err != nil {
		exception.GameException1(protocol.Code_InternalException, err)
	}
}
