// Code generated by aliensboot. DO NOT EDIT.
// source: room_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-server/module/room/core"
	"github.com/KylinHe/aliensboot-server/protocol"
)




//
func handleUpdateSeat(authID int64, gateID string, request *protocol.UpdateSeat) {
	room := core.RoomManager.GetRoomByPlayerID(authID)
	room.UpdateSeat(authID, request.GetSeatID(), request.GetOpt())
}
