// Code generated by aliensbot. DO NOT EDIT.
// source: room_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-server/module/room/core"
	"github.com/KylinHe/aliensboot-server/protocol"
)

//
func handleGameOver(authID int64, gateID string, request *protocol.GameOver) {
	room := core.RoomManager.GetRoomByPlayerID(authID)
	room.GameOver()
}


