// Code generated by aliensbot. DO NOT EDIT.
// source: room_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-server/module/room/core"
	"github.com/KylinHe/aliensboot-server/protocol"
)




//
func handleJoinSeat(authID int64, gateID string, request *protocol.JoinSeat) {
	joinRequest := request.GetRequest()
	room := core.RoomManager.EnsureRoom(joinRequest.GetRoomID())
	room.JoinSeat(authID, joinRequest.GetPlayerID(), joinRequest.GetSeatID())
}
