// Code generated by aliensbot. DO NOT EDIT.
// source: room_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-server/module/room/core"
	"github.com/KylinHe/aliensboot-server/protocol"
)




//
func handleRequestJoinSeat(authID int64, gateID string, request *protocol.RequestJoinSeat) {
	room := core.RoomManager.GetRoomByPlayerID(authID)
	joinRequest := request.GetRequest()
	joinRequest.PlayerID = authID
	room.RequestJoinGame(joinRequest)
}
