// Code generated by aliensboot. DO NOT EDIT.
// source: passport_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-core/cluster/center/service"
	"github.com/KylinHe/aliensboot-server/module/passport/core"
	"github.com/KylinHe/aliensboot-server/protocol"
)

//
func handleGetUser(ctx *service.Context, request *protocol.GetUser, response *protocol.GetUserRet) {
	var user *protocol.User
	if request.GetUid() > 0 {
		user = core.GetUserByUid(request.GetUid())
	} else if request.GetUsername() != "" {
		user = core.GetUserByUsername(request.GetUsername())
	}
	response.User = user
}
