// Code generated by aliensboot. DO NOT EDIT.
// source: passport_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-server/module/passport/core"
	"github.com/KylinHe/aliensboot-server/protocol"
	"github.com/KylinHe/aliensboot-core/cluster/center/service"
)

//
func handleModifyUserStatus(ctx *service.Context, request *protocol.ModifyUserStatus, response *protocol.ModifyUserStatusRet) {
	response.User = core.ModifyUserStatus(request.GetUid(), request.GetStatus())
}
