// Code generated by aliensbot. DO NOT EDIT.
// source: scene_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-server/protocol"
)

//
func handleMigrateOut(authID int64, gateID string, request *protocol.MigrateOut) {

}
