// Code generated by aliensbot. DO NOT EDIT.
// source: scene_interface.proto
package service

import (
	"github.com/KylinHe/aliensboot-core/mmo"
	"github.com/KylinHe/aliensboot-server/module/scene/entity"
)

//
func handleOffline(authID int64) {
	mmo.Call(entity.GetPlayerID(authID), "Logout")
}
